/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jetsonfuzz.java.gui;

import com.jetsonfuzz.java.dw.Database;
import com.jetsonfuzz.java.dw.SqlColumn;
import com.jetsonfuzz.java.dw.SqlTable;
import com.jetsonfuzz.java.dw.Warehouse;
import com.jetsonfuzz.java.main.Properties;

/**
 *
 * @author dking
 */
public class ReviewPanel extends javax.swing.JPanel {
    private Properties _props = null;
    private Database _db = null;
    private Warehouse _dw = null;
        
    /**
     * Creates new form ReviewPanel
     * @param props
     * @param db
     * @param dw
     */
    public ReviewPanel(Properties props, Database db, Warehouse dw) {
        this._props = props;
        this._db = db;
        this._dw = dw;
        
        initComponents();
        
        renderSQL();
    }

    private void renderSQL() {
        String text = "";
        
        // Show all the create commands
        for (SqlTable table : this._dw.getNewTables()) {
            text += table.getCreateCommand() + "\n";
            text += "\n";
            if (! table.isCustomTable()) {
                // Table copy insert
                text += "INSERT INTO " + table.getNewName() + " (" +
                        "SELECT * FROM " + table.getOriginalName() + ");\n";
            } else {
                // Custom table insert
                text += "INSERT INTO " + table.getNewName() + " (";

                // Label the individual columns
                int i = 0;
                
                for (SqlColumn col : table.getColumns()) {
                    if (i++ < table.getColumns().size()) {
                        text += col.getNewName() + ", ";
                    } else {
                        text += col.getNewName();
                    }
                }
                
                text += ") VALUES ("; 
            }
            
            text += "\n";
        }
        
        // Generate the FACT table SQL DDL/DML
        for (SqlTable table : this._dw.getFactTables()) {
            text += table.getCreateCommand() + "\n";

            // Insert DML for FACT Table
//            text += "\n";
//            
//            text += "INSERT INTO " + table.getNewName() + " ";
//            text += "(";
//            
//            // Define the column labels
//            int i = 0;
//            for (SqlColumn col : table.getColumns()) {
//                text += "\n\t";
//                if ((i + 1) < table.getColumns().size()) {
//                    text += col.getNewName() + ", ";
//                } else {
//                    text += col.getNewName();
//                }
//                i++;
//            }
//            
//            text += "\n) VALUES (\n";
//            
//            // Now for the values for each column
//            i = 0;
//            for (SqlColumn col : table.getColumns()) {
//                String newColName = col.getNewName();
//                SqlTable origTable = col.getOriginalTable();
//                
//                text += "\t(SELECT " + newColName + " FROM " + origTable.getNewName() + ")";
//                if ((i + 1) < table.getColumns().size()) {
//                    text += ",\n";
//                }
//                i++;
//            }
//
//            text += "\n)";
        }
                
        // Show all the insert commands
        
        this.txtSQL.setText(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSQL = new javax.swing.JTextArea();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generated SQL DDL/DML"));

        txtSQL.setColumns(20);
        txtSQL.setRows(5);
        jScrollPane1.setViewportView(txtSQL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtSQL;
    // End of variables declaration//GEN-END:variables
}
