/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jetsonfuzz.java.gui;

import com.jetsonfuzz.java.dw.Database;
import com.jetsonfuzz.java.main.Properties;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author dking
 */
public class SelectTablePanel extends javax.swing.JPanel {
    public Properties _props = null;
    public Database _db = null;
    
    /**
     * Creates new form SelectTablePanel
     * @param props
     * @param db
     */
    public SelectTablePanel(Properties props, Database db) {
        this._props = props;
        this._db = db;
        
        initComponents();
        
        load();
    }

    private void load() {
        // Retrieve the tables in the default schema
        if (! this._db.isConnected()) {
            this._db.connect();
        }
        
        ArrayList<String> tables = this._db.getTables();
        DefaultListModel<String> model = new DefaultListModel<>();

        for(String table : tables) {
            model.addElement(table);
        }

        this.listSource.setModel(model);
        
        // Close the connection
        this._db.disconnect();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listSource = new javax.swing.JList();
        btnAddAll = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSelected = new javax.swing.JList();
        btnRemoveAll = new javax.swing.JButton();
        btnRemoveTable = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddTable = new javax.swing.JButton();

        setName(""); // NOI18N

        jScrollPane1.setViewportView(listSource);

        btnAddAll.setText(">>");
        btnAddAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAllActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listSelected);

        btnRemoveAll.setText("<<");
        btnRemoveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAllActionPerformed(evt);
            }
        });

        btnRemoveTable.setText("<");
        btnRemoveTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTableActionPerformed(evt);
            }
        });

        jLabel1.setText("Source Tables");

        jLabel2.setText("Selected Tables");

        btnAddTable.setText(">");
        btnAddTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAddAll)
                        .addComponent(btnAddTable))
                    .addComponent(btnRemoveAll)
                    .addComponent(btnRemoveTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnAddTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddAll)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveAll)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTableActionPerformed
        // Get the selected tables from the source list
        int[] selectedIndices = this.listSource.getSelectedIndices();
        
        // Add those tables into a new list model
        DefaultListModel<String> model = new DefaultListModel<>();
        
        for (int id : selectedIndices) {
            model.addElement(this.listSource.getModel().getElementAt(id).toString());
            ((DefaultListModel) this.listSource.getModel()).remove(id);
        }
        
        this.listSelected.setModel(model);
    }//GEN-LAST:event_btnAddTableActionPerformed

    private void btnAddAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllActionPerformed
        // Copy the model from the source table list to the destination table
        ListModel model = this.listSource.getModel();
        this.listSelected.setModel(model);
    }//GEN-LAST:event_btnAddAllActionPerformed

    private void btnRemoveTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTableActionPerformed
        int[] selectedIndices = this.listSelected.getSelectedIndices();
        
        DefaultListModel model = (DefaultListModel) this.listSelected.getModel();
        
        for (int id : selectedIndices) {
            ((DefaultListModel) this.listSource.getModel()).addElement(model.elementAt(id));
            model.remove(id);
        }
        
        this.listSelected.setModel(model);
    }//GEN-LAST:event_btnRemoveTableActionPerformed

    private void btnRemoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAllActionPerformed
        DefaultListModel<String> modelSource = 
                (DefaultListModel<String>) this.listSelected.getModel();
        
        
    }//GEN-LAST:event_btnRemoveAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAll;
    private javax.swing.JButton btnAddTable;
    private javax.swing.JButton btnRemoveAll;
    private javax.swing.JButton btnRemoveTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listSelected;
    private javax.swing.JList listSource;
    // End of variables declaration//GEN-END:variables
}
